### ISSUE TITLE
Giving error "Proxy server is refusing connections" after setting the proxy

### ISSUE THREAD

**Issue by talktokets** [guardianproject/ProxyMob#10]
1. I have set the HTTP proxy and checked the option " Use Proxy"
2. When I tried to open a link it is showing the error "Proxy server is refusing connections" and the page is not opening.
3. The page is opening without setting proxy

Can you please help with the above situation ?

_Note_
Attaching Screenshot 
![sc20130607-184204](https://f.cloud.github.com/assets/3233471/623826/890c65a0-cf74-11e2-8a62-131ffd3da03a.jpg)

**Comment by eywon** [comment]
I have orbot and orfox and it sti says "proxy server is refusing connection" help please.
