### ISSUE TITLE
Dangerous due to conceptual flaw

### ISSUE THREAD

**Issue by chaos095** [guardianproject/ProxyMob#18]
This add-on is dangerous in combination with orbot (or any other anonymizing service).
Firefox on Android pulls favicons without respecting proxy preferences. Thus, the real IP address is visible for the favicon's GET request.
See here for details: https://bugzilla.mozilla.org/show_bug.cgi?id=507641#c12

**Comment by n8fr8** [comment]
We've removed this from Mozilla's add-on store, and are going to stop promoting it on our site shortly. The focus on it was proxying and not full anonymity, but yes the favicon bug in Firefox is a big problem.

We are working on a port of Tor Browser to Android which you can track here:
https://dev.guardianproject.info/projects/orfox-private-browser/
